<?php

return [

    'neon' => [
        'nombre' => 'Neón',
        'descripcion' => 'Oscuro y vibrante',
        'preview' => ['#120d02', '#00d4e8', '#c19849'],
        'vars' => [
            '--mg-gold' => '#c19849',
            '--mg-gold-glow' => 'rgba(193,152,73,0.5)',
            '--mg-gray' => '#535353',
            '--mg-neon-cyan' => '#00d4e8',
            '--mg-neon-cyan-glow' => 'rgba(0,212,232,0.25)',
            '--mg-neon-lime' => '#c8df00',
            '--mg-body-bg' => '#120d02',
            '--mg-body-bg-2' => '#1a1306',
            '--mg-card-bg' => '#1a1306',
            '--mg-card-bg-2' => '#201808',
            '--mg-text' => '#e8dcc8',
            '--mg-text-muted' => '#9a8870',
            '--mg-border' => '#2d2410',
            '--mg-header-bg' => '#0d0901',
            '--mg-input-bg' => '#201808',
            '--mg-input-border' => '#3d3020',
            '--mg-btn-primary-bg' => '#c19849',
            '--mg-btn-primary-text' => '#0d0901',
            '--mg-btn-primary-hover' => '#d4a955',
            '--mg-franja-available-border' => '#00d4e8',
            '--mg-franja-available-glow' => 'rgba(0,212,232,0.15)',
            '--mg-franja-selected-bg' => 'rgba(0,212,232,0.2)',
            '--mg-hora-color' => '#c8df00',
        ],
    ],

    'clasico' => [
        'nombre' => 'Clásico',
        'descripcion' => 'Limpio y profesional',
        'preview' => ['#f7fafc', '#2c5282', '#e2883c'],
        'vars' => [
            '--mg-gold' => '#2c5282',
            '--mg-gold-glow' => 'rgba(44,82,130,0.3)',
            '--mg-gray' => '#718096',
            '--mg-neon-cyan' => '#3182ce',
            '--mg-neon-cyan-glow' => 'rgba(49,130,206,0.2)',
            '--mg-neon-lime' => '#38a169',
            '--mg-body-bg' => '#f7fafc',
            '--mg-body-bg-2' => '#edf2f7',
            '--mg-card-bg' => '#ffffff',
            '--mg-card-bg-2' => '#f7fafc',
            '--mg-text' => '#1a202c',
            '--mg-text-muted' => '#718096',
            '--mg-border' => '#e2e8f0',
            '--mg-header-bg' => '#2c5282',
            '--mg-input-bg' => '#ffffff',
            '--mg-input-border' => '#cbd5e0',
            '--mg-btn-primary-bg' => '#2c5282',
            '--mg-btn-primary-text' => '#ffffff',
            '--mg-btn-primary-hover' => '#2a4a7f',
            '--mg-franja-available-border' => '#3182ce',
            '--mg-franja-available-glow' => 'rgba(49,130,206,0.1)',
            '--mg-franja-selected-bg' => 'rgba(49,130,206,0.15)',
            '--mg-hora-color' => '#38a169',
        ],
    ],

    'pastel' => [
        'nombre' => 'Pastel',
        'descripcion' => 'Suave y acogedor',
        'preview' => ['#fdf4ff', '#8b5cf6', '#f472b6'],
        'vars' => [
            '--mg-gold' => '#8b5cf6',
            '--mg-gold-glow' => 'rgba(139,92,246,0.3)',
            '--mg-gray' => '#a78bfa',
            '--mg-neon-cyan' => '#f472b6',
            '--mg-neon-cyan-glow' => 'rgba(244,114,182,0.2)',
            '--mg-neon-lime' => '#34d399',
            '--mg-body-bg' => '#fdf4ff',
            '--mg-body-bg-2' => '#f3e8ff',
            '--mg-card-bg' => '#ffffff',
            '--mg-card-bg-2' => '#fdf4ff',
            '--mg-text' => '#4c1d95',
            '--mg-text-muted' => '#7c3aed',
            '--mg-border' => '#ddd6fe',
            '--mg-header-bg' => '#7c3aed',
            '--mg-input-bg' => '#ffffff',
            '--mg-input-border' => '#c4b5fd',
            '--mg-btn-primary-bg' => '#8b5cf6',
            '--mg-btn-primary-text' => '#ffffff',
            '--mg-btn-primary-hover' => '#7c3aed',
            '--mg-franja-available-border' => '#f472b6',
            '--mg-franja-available-glow' => 'rgba(244,114,182,0.15)',
            '--mg-franja-selected-bg' => 'rgba(244,114,182,0.2)',
            '--mg-hora-color' => '#34d399',
        ],
    ],

];
